trigger:
  batch: true
  branches:
    include:
    - master
    - releases/*

pool:
  vmImage: 'ubuntu-latest'

# Set variables once
variables:
  configuration: Release

steps:
- script: dotnet restore
- script: dotnet build -c ${configuration}

- publish: $(System.DefaultWorkingDirectory)/**/*.nupkg
  artifact: NuGetPackage